### ISSUE TITLE
Delete group

### ISSUE THREAD

**Issue by StanisGit** [bbernhard/signal-cli-rest-api#387]
### The problem

I created a group with only one memeber and an empty name:
`curl -X POST -H "Content-Type: application/json" -d '{"name": "", "members": ["+123456789012"]}' 'http://localhost:8080/v1/groups/+123456789012'`
Now I want to delete the group. This group is not displayed in the Signal, but it is displayed on request:
`curl -X GET -H "Content-Type: application/json" 'http://localhost:8080/v1/groups/+123456789012'`
For delete the group I am executing the command in Docker terminal:
`curl -X DELETE -H "Content-Type: application/json" 'http://localhost:8080/v1/groups/+123456789012/group.dHl...V0QT0='`
or
`curl -X DELETE -H "Content-Type: application/json" 'http://localhost:8080/v1/groups/+380978483884/dHl...V0QT0='`
but groups are not removed, although I don't get an error, just an empty string in the response.
I still see these groups on request:
`curl -X GET -H "Content-Type: application/json" 'http://localhost:8080/v1/groups/+123456789012'`

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
Have you tried calling the `receive` endpoint afterwards?

**Comment by StanisGit** [comment]
I completed the request:
`curl -X GET -H "Content-Type: application/json" 'http://localhost:8080/v1/receive/+123456789012'`
then
`curl -X GET -H "Content-Type: application/json" 'http://localhost:8080/v1/groups/+123456879012'`
What command should I enter for `receive `endpoint afterwards?

**Comment by bbernhard** [comment]
Just to get it right, you called the `receive` endpoint after you've removed the group, right?

**Comment by bastikempken** [comment]
Same problem for me, call `receive` afterwards has no effect

**Comment by Kuhkaefer** [comment]
Deleting a group does not work for me either. I receive an empty 500 response and a `receive` afterwards does not have an effect.
The logs in debug mode show:

```
2023/09/28 07:48:44 [Recovery] 2023/09/28 - 07:48:44 panic recovered:
runtime error: invalid memory address or nil pointer dereference                                                                                               
/usr/local/go/src/runtime/panic.go:260 (0x44d4dc)                                                                                                              
/usr/local/go/src/runtime/signal_unix.go:841 (0x44d4ac)                                                                                                        
/tmp/signal-cli-rest-api-src/client/cli.go:37 (0x9c7424)                                                                                                       
/tmp/signal-cli-rest-api-src/client/client.go:914 (0x9da228)                                                                                                   
/tmp/signal-cli-rest-api-src/api/api.go:817 (0x9d9ffb)                                                                                                         
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x935fa1)                                                                                          
[GIN] 2023/09/28 - 07:48:44 | 500 |     698.679µs |      172.17.0.1 | DELETE   "/v1/groups/+MYNUMBER/group.MYGROUPID="                                                                                                                                                 
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102 (0x935f8c)                                                                                         
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x9350c6)                                                                                          
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240 (0x9350a9)                                                                                           
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x93412a)                                                                                          
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620 (0x933db1)                                                                                              
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576 (0x9338dc)                                                                                              
/usr/local/go/src/net/http/server.go:2936 (0x701815)                                                                                                           
/usr/local/go/src/net/http/server.go:1995 (0x6fcd31)                                                                                                           
/usr/local/go/src/runtime/asm_amd64.s:1598 (0x469680)
```

**Comment by Kuhkaefer** [comment]
With version 0.68, the logs show:

```
2023/09/28 08:21:25 [Recovery] 2023/09/28 - 08:21:25 panic recovered:
runtime error: invalid memory address or nil pointer dereference                                                                                               
/usr/local/go/src/runtime/panic.go:260 (0x44d53c)                                                                                                              
/usr/local/go/src/runtime/signal_unix.go:841 (0x44d50c)                                                                                                        
/tmp/signal-cli-rest-api-src/client/cli.go:37 (0x9c8364)                                                                                                       
/tmp/signal-cli-rest-api-src/client/client.go:978 (0x9dbca8)                                                                                                   
/tmp/signal-cli-rest-api-src/api/api.go:835 (0x9dba7b)                                                                                                         
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x936961)                                                                                          
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102 (0x93694c)                                                                                         
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x935a86)                                                                                          
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240 (0x935a69)                                                                                           
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x934aea)                                                                                          
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620 (0x934771)                                                                                              
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576 (0x93429c)                                                                                              
/usr/local/go/src/net/http/server.go:2936 (0x701af5)                                                                                                           
/usr/local/go/src/net/http/server.go:1995 (0x6fd011)                                                                                                           
/usr/local/go/src/runtime/asm_amd64.s:1598 (0x4696e0) 

[GIN] 2023/09/28 - 08:21:25 | 500 |     641.618µs |      172.17.0.1 | DELETE   "/v1/groups/+MYNUMBER/group.MYGROUPID="
```

**Comment by Kuhkaefer** [comment]
And slightly different for version 0.69:

```
2023/10/03 21:51:25 [Recovery] 2023/10/03 - 21:51:25 panic recovered:
runtime error: invalid memory address or nil pointer dereference                                                                                               
/usr/local/go/src/runtime/panic.go:260 (0x44d53c)                                                                                                              
/usr/local/go/src/runtime/signal_unix.go:841 (0x44d50c)                                                                                                        
/tmp/signal-cli-rest-api-src/client/cli.go:37 (0x9c8364)                                                                                                       
/tmp/signal-cli-rest-api-src/client/client.go:996 (0x9dc468)                                                                                                   
/tmp/signal-cli-rest-api-src/api/api.go:840 (0x9dc23b)                                                                                                         
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x936961)                                                                                          
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102 (0x93694c)                                                                                         
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x935a86)                                                                                          
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240 (0x935a69)                                                                                           
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x934aea)                                                                                          
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620 (0x934771)                                                                                              
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576 (0x93429c)                                                                                              
/usr/local/go/src/net/http/server.go:2936 (0x701af5)                                                                                                           
/usr/local/go/src/net/http/server.go:1995 (0x6fd011)                                                                                                           
/usr/local/go/src/runtime/asm_amd64.s:1598 (0x4696e0)                                                                                                          
                                                                                                                                                               
[GIN] 2023/10/03 - 21:51:25 | 500 |     266.504µs |      172.17.0.1 | DELETE   "/v1/groups/+4915156317857/group.UzVBOW14bmJiSUwzWjFrdFRyMUhmMXR4NUJGb1ptdjhKb1RTcTJWT1VkOD0="
```

**Comment by bbernhard** [comment]
Sorry, completely missed that. I'll have a look

**Comment by bbernhard** [comment]
> And slightly different for version 0.69:
> 
> ```
> 2023/10/03 21:51:25 [Recovery] 2023/10/03 - 21:51:25 panic recovered:
> runtime error: invalid memory address or nil pointer dereference                                                                                               
> /usr/local/go/src/runtime/panic.go:260 (0x44d53c)                                                                                                              
> /usr/local/go/src/runtime/signal_unix.go:841 (0x44d50c)                                                                                                        
> /tmp/signal-cli-rest-api-src/client/cli.go:37 (0x9c8364)                                                                                                       
> /tmp/signal-cli-rest-api-src/client/client.go:996 (0x9dc468)                                                                                                   
> /tmp/signal-cli-rest-api-src/api/api.go:840 (0x9dc23b)                                                                                                         
> /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x936961)                                                                                          
> /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102 (0x93694c)                                                                                         
> /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x935a86)                                                                                          
> /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240 (0x935a69)                                                                                           
> /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x934aea)                                                                                          
> /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620 (0x934771)                                                                                              
> /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576 (0x93429c)                                                                                              
> /usr/local/go/src/net/http/server.go:2936 (0x701af5)                                                                                                           
> /usr/local/go/src/net/http/server.go:1995 (0x6fd011)                                                                                                           
> /usr/local/go/src/runtime/asm_amd64.s:1598 (0x4696e0)                                                                                                          
>                                                                                                                                                                
> [GIN] 2023/10/03 - 21:51:25 | 500 |     266.504µs |      172.17.0.1 | DELETE   "/v1/groups/MYNUMBER/MYGROOUPID"
> ```

Should be fixed with the next release.

@bastikempken @StanisGit Are you sure that you are still a member of that group? Otherwise you can't remove the group. There will be an info printed in the next release when this happens.

**Comment by bastikempken** [comment]
i think you are right, i left the group but was confused why the group itself still exist for me (without me as a member). But its the same in the mobile app i guess, leaving the group and deleting the group itself are separated processes
